In [1]:
import numpy as np

In [2]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
listarr.shape

(3, 3)

In [4]:
listarr.size

9

In [5]:
zeros = np.zeros((3,3), np.int64)

In [6]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
rng = np.arange(1, 16)

In [8]:
rng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
lspace = np.linspace(1, 4, 4)

In [10]:
lspace

array([1., 2., 3., 4.])

In [11]:
iden = np.identity(3, np.int64)

In [12]:
iden

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
arg = np.arange(1,101)

In [14]:
arg

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
arg = arg.reshape(10,10)

In [16]:
arg

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
arg

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
arg.sum(axis=0)

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [19]:
arg.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [25]:
one = np.array([4,3,1,2])

In [26]:
print(one.argmax())

0


In [27]:
print(one.argmin())

2


In [28]:
print(one.argsort())

[2 3 1 0]


In [29]:
two = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
print(two.argmax())

8


In [33]:
print(two.argmax(axis=0))

[2 2 2]


In [34]:
two2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
print(two // two2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [40]:
print(np.count_nonzero(two2))

9


In [41]:
import sys

In [45]:
py_arr = [1, 2, 3, 4, 5]
np_arr = np.array(py_arr)
print(sys.getsizeof(1) * len(np_arr))
print(np_arr.itemsize * np_arr.size)

140
40


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])